=== baranyai2/RV4TJXxmlGyak/XMLFeladatRV4TJX/XMLSchemaRV4TJX.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" targetNamespace="beadando" xmlns="beadando" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="kiszallitas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="rendelok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded"
                                        name="rendelo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nev"
                                                    type="xs:string" />
                                        <xs:element name="email"
                                                    type="xs:string" />
                                        <xs:element name="lakcim">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="iranyitoszam"
                                                                type="xs:unsignedLong" />
                                                    <xs:element name="varos"
                                                                type="xs:string" />
                                                    <xs:element name="utca"
                                                                type="xs:string" />
                                                    <xs:element name="hazszam"
                                                                type="xs:unsignedInt" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="rendeloid"
                                                  type="xs:unsignedByte"
                                                  use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="rendelesek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded"
                                        name="rendeles">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ar"
                                                    type="xs:unsignedInt" />
                                        <xs:element name="kiszallido"
                                                    type="xs:unsignedInt" />
                                        <xs:element name="rendelesido"
                                                    type="xs:date" />
                                    </xs:sequence>
                                    <xs:attribute name="rendelesid"
                                                  type="xs:unsignedByte"
                                                  use="required" />
                                    <xs:attribute name="rendeloid"
                                                  type="xs:unsignedByte"
                                                  use="required" />
                                    <xs:attribute name="futid"
                                                  type="xs:unsignedByte"
                                                  use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="futarok">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded"
                                    name="futar">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nev"
                                                type="xs:string" />
                                    <xs:element name="telefonszam"
                                                type="xs:unsignedLong" />
                                    <xs:element name="fizetes"
                                                type="xs:unsignedInt" />
                                </xs:sequence>
                                <xs:attribute name="futid"
                                              type="xs:unsignedByte"
                                              use="required" />
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
                <xs:element name="etelek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded"
                                        name="etel">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nev"
                                                    type="xs:string" />
                                        <xs:element name="elkeszitido"
                                                    type="xs:unsignedInt" />
                                        <xs:element name="feltetek"
                                                    type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="etelid"
                                                  type="xs:unsignedByte"
                                                  use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="tartalmazas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded"
                                        name="tartalmaz">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="elkeszito"
                                                    type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="etelid"
                                                  type="xs:unsignedByte"
                                                  use="required" />
                                    <xs:attribute name="rendelesid"
                                                  type="xs:unsignedByte"
                                                  use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== baranyai2/RV4TJXxmlGyak/XMLRV4TJXnew.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><kiszallitas xmlns="beadando" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="beadando XMLSchemaRV4TJX.xsd">
    <rendelok>
        <rendelo rendeloid="0">
            <nev>Példa János</nev>
            <email>kpeti@gmail.com</email>
            <lakcim>
                <iranyitoszam>1234</iranyitoszam>
                <varos>Kukutyin</varos>
                <utca>Kosstuh Lajos</utca>
                <hazszam>123</hazszam>
            </lakcim>
        </rendelo>
        <rendelo rendeloid="1">
            <nev>Nagy Sándor</nev>
            <email>sanyeszka@gmail.com</email>
            <lakcim>
                <iranyitoszam>1234</iranyitoszam>
                <varos>Kukutyin</varos>
                <utca>Petőfi Sándor</utca>
                <hazszam>321</hazszam>
            </lakcim>
        </rendelo>
        <rendelo rendeloid="2">
            <nev>Példa Péter</nev>
            <email>petike@gmail.com</email>
            <lakcim>
                <iranyitoszam>1235</iranyitoszam>
                <varos>Alsókukutyin</varos>
                <utca>Főtér</utca>
                <hazszam>12</hazszam>
            </lakcim>
        </rendelo>
        <rendelo rendeloid="3">
            <nev>Jócska János</nev>
            <email>joja@gmail.com</email>
            <lakcim>
                <iranyitoszam>1234</iranyitoszam>
                <varos>Kukutyin</varos>
                <utca>Kossith Lajos</utca>
                <hazszam>12</hazszam>
            </lakcim>
        </rendelo>
    </rendelok>
    <rendelesek>
        <rendeles futid="0" rendelesid="0" rendeloid="2">
            <ar>20000</ar>
            <kiszallido>30</kiszallido>
            <rendelesido>2020-11-10</rendelesido>
        </rendeles>
        <rendeles futid="1" rendelesid="1" rendeloid="0">
            <ar>3500</ar>
            <kiszallido>20</kiszallido>
            <rendelesido>2020-11-11</rendelesido>
        </rendeles>
        <rendeles futid="1" rendelesid="2" rendeloid="1">
            <ar>7500</ar>
            <kiszallido>20</kiszallido>
            <rendelesido>2020-11-11</rendelesido>
        </rendeles>
        <rendeles futid="2" rendelesid="3" rendeloid="3">
            <ar>5000</ar>
            <kiszallido>30</kiszallido>
            <rendelesido>2020-11-12</rendelesido>
        </rendeles>
        <rendeles futid="1" rendelesid="4" rendeloid="0">
            <ar>3500</ar>
            <kiszallido>15</kiszallido>
            <rendelesido>2020-11-15</rendelesido>
        </rendeles>
        <rendeles futid="0" rendelesid="5" rendeloid="1">
            <ar>9000</ar>
            <kiszallido>25</kiszallido>
            <rendelesido>2020-11-16</rendelesido>
        </rendeles>
    </rendelesek>
    <futarok>
        <futar futid="0">
            <nev>Kiss Csaba</nev>
            <telefonszam>06709453211</telefonszam>
            <fizetes>25000</fizetes>
        </futar>
        <futar futid="1">
            <nev>Nagy Béla</nev>
            <telefonszam>06303625510</telefonszam>
            <fizetes>30000</fizetes>
        </futar>
        <futar futid="2">
            <nev>Szabó Alen</nev>
            <telefonszam>0620</telefonszam>
            <fizetes>25000</fizetes>
        </futar>
    </futarok>
    <etelek>
        <etel etelid="0">
            <nev>Pepperoni pizza</nev>
            <elkeszitido>12</elkeszitido>
            <feltetek>Pepperoni</feltetek>
        </etel>
        <etel etelid="1">
            <nev>Hawaii pizza</nev>
            <elkeszitido>12</elkeszitido>
            <feltetek>Ananász</feltetek>
        </etel>
        <etel etelid="2">
            <nev>Hamburger</nev>
            <elkeszitido>8</elkeszitido>
            <feltetek>Húspogácsa</feltetek>
        </etel>
        <etel etelid="3">
            <nev>Rántott hús</nev>
            <elkeszitido>20</elkeszitido>
            <feltetek>Sültkrumpli</feltetek>
        </etel>
        <etel etelid="4">
            <nev>Májas rizotto</nev>
            <elkeszitido>35</elkeszitido>
            <feltetek>Rizs</feltetek>
        </etel>
    </etelek>
    <tartalmazas>
        <tartalmaz etelid="1" rendelesid="0">
            <elkeszito>Pista</elkeszito>
        </tartalmaz>
        <tartalmaz etelid="2" rendelesid="0">
            <elkeszito>Pista</elkeszito>
        </tartalmaz>
        <tartalmaz etelid="3" rendelesid="0">
            <elkeszito>Pista</elkeszito>
        </tartalmaz>
        <tartalmaz etelid="4" rendelesid="1">
            <elkeszito>János</elkeszito>
        </tartalmaz>
        <tartalmaz etelid="0" rendelesid="1">
            <elkeszito>János</elkeszito>
        </tartalmaz>
        <tartalmaz etelid="1" rendelesid="2">
            <elkeszito>János</elkeszito>
        </tartalmaz>
        <tartalmaz etelid="3" rendelesid="3">
            <elkeszito>Pista</elkeszito>
        </tartalmaz>
        <tartalmaz etelid="2" rendelesid="3">
            <elkeszito>Pista</elkeszito>
        </tartalmaz>
        <tartalmaz etelid="0" rendelesid="4">
            <elkeszito>János</elkeszito>
        </tartalmaz>
        <tartalmaz etelid="0" rendelesid="5">
            <elkeszito>János</elkeszito>
        </tartalmaz>
    </tartalmazas>
</kiszallitas>

=== baranyai2/RV4TJXxmlGyak/XMLFeladatRV4TJX/XMLRV4TJX.xml
<?xml version="1.0" encoding="UTF-8"?>

<kiszallitas xmlns="beadando" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="beadando XMLSchemaRV4TJX.xsd">
    <rendelok>
        <rendelo rendeloid="0">
            <nev>Kiss Péter</nev>
            <email>kpeti@gmail.com</email>
            <lakcim>
                <iranyitoszam>1234</iranyitoszam>
                <varos>Kukutyin</varos>
                <utca>Kosstuh Lajos</utca>
                <hazszam>123</hazszam>
            </lakcim>
        </rendelo>
        <rendelo rendeloid="1">
            <nev>Nagy Sándor</nev>
            <email>sanyesz@gmail.com</email>
            <lakcim>
                <iranyitoszam>1234</iranyitoszam>
                <varos>Kukutyin</varos>
                <utca>Petőfi Sándor</utca>
                <hazszam>321</hazszam>
            </lakcim>
        </rendelo>
        <rendelo rendeloid="2">
            <nev>Példa Péter</nev>
            <email>petike@gmail.com</email>
            <lakcim>
                <iranyitoszam>1235</iranyitoszam>
                <varos>Alsókukutyin</varos>
                <utca>Főtér</utca>
                <hazszam>12</hazszam>
            </lakcim>
        </rendelo>
        <rendelo rendeloid="3">
            <nev>Jócska János</nev>
            <email>joja@gmail.com</email>
            <lakcim>
                <iranyitoszam>1234</iranyitoszam>
                <varos>Kukutyin</varos>
                <utca>Kossith Lajos</utca>
                <hazszam>12</hazszam>
            </lakcim>
        </rendelo>
    </rendelok>
    <rendelesek>
        <rendeles rendelesid="0" rendeloid="2" futid="0">
            <ar>20000</ar>
            <kiszallido>30</kiszallido>
            <rendelesido>2020-11-10</rendelesido>
        </rendeles>
        <rendeles rendelesid="1" rendeloid="0" futid="1">
            <ar>3500</ar>
            <kiszallido>20</kiszallido>
            <rendelesido>2020-11-11</rendelesido>
        </rendeles>
        <rendeles rendelesid="2" rendeloid="1" futid="1">
            <ar>7500</ar>
            <kiszallido>20</kiszallido>
            <rendelesido>2020-11-11</rendelesido>
        </rendeles>
        <rendeles rendelesid="3" rendeloid="3" futid="2">
            <ar>5000</ar>
            <kiszallido>30</kiszallido>
            <rendelesido>2020-11-12</rendelesido>
        </rendeles>
        <rendeles rendelesid="4" rendeloid="0" futid="1">
            <ar>3500</ar>
            <kiszallido>15</kiszallido>
            <rendelesido>2020-11-15</rendelesido>
        </rendeles>
        <rendeles rendelesid="5" rendeloid="1" futid="0">
            <ar>9000</ar>
            <kiszallido>25</kiszallido>
            <rendelesido>2020-11-16</rendelesido>
        </rendeles>
    </rendelesek>
    <futarok>
        <futar futid="0">
            <nev>Schmidt Henrik</nev>
            <telefonszam>06709453211</telefonszam>
            <fizetes>20000</fizetes>
        </futar>
        <futar futid="1">
            <nev>German Jakab</nev>
            <telefonszam>06303625510</telefonszam>
            <fizetes>20000</fizetes>
        </futar>
        <futar futid="2">
            <nev>Szabó Alen</nev>
            <telefonszam>0620</telefonszam>
            <fizetes>20000</fizetes>
        </futar>
    </futarok>
    <etelek>
        <etel etelid="0">
            <nev>Pepperoni pizza</nev>
            <elkeszitido>12</elkeszitido>
            <feltetek>Pepperoni</feltetek>
        </etel>
        <etel etelid="1">
            <nev>Sonkás pizza</nev>
            <elkeszitido>12</elkeszitido>
            <feltetek>Sonka</feltetek>
        </etel>
        <etel etelid="2">
            <nev>Hamburger</nev>
            <elkeszitido>8</elkeszitido>
            <feltetek>Húspogácsa</feltetek>
        </etel>
        <etel etelid="3">
            <nev>Rántott hús</nev>
            <elkeszitido>20</elkeszitido>
            <feltetek>Sültkrumpli</feltetek>
        </etel>
        <etel etelid="4">
            <nev>Májas rizotto</nev>
            <elkeszitido>35</elkeszitido>
            <feltetek>Rizs</feltetek>
        </etel>
    </etelek>
    <tartalmazas>
        <tartalmaz etelid="1" rendelesid="0">
            <elkeszito>Pista</elkeszito>
        </tartalmaz>
        <tartalmaz etelid="2" rendelesid="0">
            <elkeszito>Pista</elkeszito>
        </tartalmaz>
        <tartalmaz etelid="3" rendelesid="0">
            <elkeszito>Pista</elkeszito>
        </tartalmaz>
        <tartalmaz etelid="4" rendelesid="1">
            <elkeszito>János</elkeszito>
        </tartalmaz>
        <tartalmaz etelid="0" rendelesid="1">
            <elkeszito>János</elkeszito>
        </tartalmaz>
        <tartalmaz etelid="1" rendelesid="2">
            <elkeszito>János</elkeszito>
        </tartalmaz>
        <tartalmaz etelid="3" rendelesid="3">
            <elkeszito>Pista</elkeszito>
        </tartalmaz>
        <tartalmaz etelid="2" rendelesid="3">
            <elkeszito>Pista</elkeszito>
        </tartalmaz>
        <tartalmaz etelid="0" rendelesid="4">
            <elkeszito>János</elkeszito>
        </tartalmaz>
        <tartalmaz etelid="0" rendelesid="5">
            <elkeszito>János</elkeszito>
        </tartalmaz>
    </tartalmazas>
</kiszallitas>
